// Task Board Module (extracted from orchestrator.mjs in S67)
// Task board markdown generation and dependency status checking

import { writeFileSync } from 'fs';

// Module-level dependencies (set via init)
let getAgents = () => [];
let CONFIG = null;
let TASK_BOARD = '';
let timestampFn = () => '';
let getTestCommandFn = () => '';
let parseHandoffMetaFn = () => ({});

/**
 * Initialize task board with orchestrator context.
 * @param {{ getAgents: Function, config: object, taskBoardPath: string, timestamp: Function, getTestCommand: Function, parseHandoffMeta: Function }} ctx
 */
export function initTaskBoard(ctx) {
  getAgents = ctx.getAgents;
  CONFIG = ctx.config;
  TASK_BOARD = ctx.taskBoardPath;
  timestampFn = ctx.timestamp;
  getTestCommandFn = ctx.getTestCommand;
  parseHandoffMetaFn = ctx.parseHandoffMeta;
}

export function isDepSatisfied(status) {
  return status === 'complete' || status === 'all-done';
}

export function generateTaskBoard(round, testStatus, consecutiveFailures) {
  const AGENTS = getAgents();
  const agentStatuses = AGENTS.map(agent => {
    const meta = parseHandoffMetaFn(agent.id);
    const depsMet = agent.dependsOn.every(depId => {
      const depMeta = parseHandoffMetaFn(depId);
      return isDepSatisfied(depMeta.status);
    });
    const effectiveStatus = meta.status === 'all-done' ? 'all-done'
      : meta.status === 'complete' ? 'complete (stretch goals)'
      : !depsMet ? `blocked (waiting for ${agent.dependsOn.join(', ')})`
      : meta.status;

    return { ...agent, meta, effectiveStatus, depsMet };
  });

  const allFilesModified = agentStatuses.flatMap(a =>
    a.meta.filesModified.map(f => `${f} (${a.id})`)
  );

  let board = `# Jousting MVP — Shared Task Board
> Generated by orchestrator. Round ${round}. Agents: READ ONLY (do not edit this file).
> Last updated: ${timestampFn()}

## System Status
- **Round**: ${round} of ${CONFIG.maxRounds}
- **Tests**: ${testStatus ?? 'not yet run'}
- **Consecutive test failures**: ${consecutiveFailures}
${consecutiveFailures >= 2 ? '- **WARNING**: Tests have been failing. Focus on fixing test failures before new features!' : ''}

## Agent Status
| Agent | Type | Status | Dependencies |
|-------|------|--------|-------------|
${agentStatuses.map(a =>
  `| ${a.id} | ${a.type} | ${a.effectiveStatus} | ${a.dependsOn.length ? a.dependsOn.join(', ') : 'none'} |`
).join('\n')}

## Files Modified This Session
${allFilesModified.length ? allFilesModified.map(f => `- ${f}`).join('\n') : '(none yet)'}

## Messages Between Agents
${agentStatuses.filter(a => a.meta.notes).map(a => `- **${a.id}**: ${a.meta.notes}`).join('\n') || '(none)'}

## Coordination Rules
1. Only edit files assigned to you (see your handoff for file ownership)
2. If you need to edit App.tsx (shared), note the change in your handoff under "Deferred App.tsx Changes" — the orchestrator will coordinate
3. Do NOT run git commands — the orchestrator handles all commits
4. Do NOT edit this task board — it is auto-generated
5. Run \`${getTestCommandFn()}\` before writing your final handoff to confirm tests pass
6. Write your updated handoff with the ## META section at the top

## Reference
See CLAUDE.md for file locations and architecture.
`;

  writeFileSync(TASK_BOARD, board);
  return board;
}
